steps:
  # run tests
  - name: maven
    entrypoint: mvn
    args: ["clean", "test"]

  # package the jar
  - name: maven
    entrypoint: mvn
    args: ["install", "-Dmaven.test.skip=true"]

  # build the container image
  - name: gcr.io/cloud-builders/docker
    args: [ build, -t, gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA, . ]

  # push the container image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args: [ push, gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA ]

images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
