spring:
  application:
    name: stackrs-service
  profiles:
    active: DEV
security:
  config:
    binance_api_key: ${sm://binance_api_key}
    binance_api_secret: ${sm://binance_api_secret}
    coinmarketcap_api_key: ${sm://coinmarketcap_api_key}
api:
  config:
    coinmarketcap:
      base_uri: https://sandbox-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 100
      convert: BTC


