spring:
  application:
    name: stackrs-service
  profiles:
    active: prod
security:
  config:
    binance_api_key: ${sm://binance_api_key}
    binance_api_secret: ${sm://binance_api_secret}
    coinmarketcap_api_key: ${sm://coinmarketcap_api_key}
algo:
  target_coin: BTC

---

spring:
  profiles: test
api:
  config:
    coinmarketcap:
      base_uri: https://sandbox-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 100
    binance:
      base_uri: https://api.binance.com
      exchange_info_url: /api/v3/exchangeInfo
      account_snapshot_uri: /sapi/v1/accountSnapshot
      timeout: 10000
      snap_type: SPOT

---

spring:
  profiles: prod
api:
  config:
    coinmarketcap:
      base_uri: https://pro-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 100
    binance:
      base_uri: https://api.binance.com
      exchange_info_url: /api/v3/exchangeInfo
      account_snapshot_uri: /sapi/v1/accountSnapshot
      timeout: 10000
      snap_type: SPOT
