spring:
  application:
    name: stackrs-service
  profiles:
    active: prod
security:
  config:
    binance_api_key: ${sm://binance_api_key}
    binance_api_secret: ${sm://binance_api_secret}
    coinmarketcap_api_key: ${sm://coinmarketcap_api_key}

---

spring:
  profiles: test
api:
  config:
    coinmarketcap:
      base_uri: https://sandbox-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 100
      convert: BTC
    binance:
      base_uri: https://api.binance.com/api/v3
      exchange_info_url: /exchangeInfo
      timeout: 10000

---

spring:
  profiles: prod
api:
  config:
    coinmarketcap:
      base_uri: https://pro-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 100
      convert: BTC
    binance:
      base_uri: https://api.binance.com/api/v3
      exchange_info_url: /exchangeInfo
      timeout: 10000
