spring:
  application:
    name: stackrs-service
  profiles:
    active: prod
security:
  config:
    binance_api_key: ${sm://binance_api_key}
    binance_api_secret: ${sm://binance_api_secret}
    coinmarketcap_api_key: ${sm://coinmarketcap_api_key}
algo:
  base_fiat: GBP
  target_fiat_amount: 15
  target_coin: BTC
  target_min_balance: 0.00006683
  target_profit: 0.065

---

spring:
  profiles: test
api:
  config:
    coinmarketcap:
      base_uri: https://sandbox-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 125

---

spring:
  profiles: prod
api:
  config:
    coinmarketcap:
      base_uri: https://pro-api.coinmarketcap.com/v1
      latest_listings_uri: /cryptocurrency/listings/latest
      timeout: 10000
      start: 1
      limit: 125
